name: Lowest Dependencies

on:
  workflow_dispatch:
  pull_request:

jobs:
  lowest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
      - run: composer update --prefer-lowest --prefer-stable --no-interaction
      - run: composer test